name: E2E Playwright (External Repo)
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install app dependencies
        run: npm ci

      - name: Build app
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script. Skipping build."
          fi

      - name: Start app server
        run: |
          npm start &
          npx --yes wait-on http://localhost:3000

      - name: Clone Playwright test repository
        run: git clone https://github.com/unnath123/pract.git test-repo

      - name: Install test dependencies
        working-directory: test-repo
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: test-repo
        env:
          CI: true
          BASE_URL: http://localhost:3000
        run: |
          npx xvfb-run -a npx playwright test --config=playwright.config.ts

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_number }}
          path: |
            test-repo/playwright-report/
            test-repo/test-results/
            test-repo/allure-results/
          retention-days: 30
