name: Playwright Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Clone test repository
      run: |
        git clone https://github.com/unnath123/practseone.git test-repo
        cd test-repo
        npm ci
        npx playwright install --with-deps
    
    - name: Build project
      run: npm run build
    
    - name: Start application server
      run: |
        npm start &
        sleep 30  # Wait for server to start
    
    - name: Run Playwright tests from external repo
      run: |
        cd test-repo
        npx playwright test --config=playwright.config.ts
      env:
        CI: true
        BASE_URL: http://localhost:3000
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ github.run_number }}
        path: |
          test-repo/playwright-report/
          test-repo/test-results/
          test-repo/allure-results/
        retention-days: 30
